#!/usr/bin/env python3
"""Transcribe the C++ QuantLib Sobol / lattice data tables into PQuantLib.

# C++ parity: ql/math/randomnumbers/{sobolrsg,primitivepolynomials,
# latticerules}.cpp (v1.43).

These tables are pure data — 21 200 primitive polynomials modulo two, ten
families of Sobol free-direction integers (the largest, Joe-Kuo D6, covers
21 200 dimensions) and four lattice-rule generating vectors of 3 600 entries
each. Retyping them by hand is not an option, and burying them in a Python
literal would produce multi-megabyte source files, so they are emitted as
plain text resources next to the modules that read them.

Run from the repo root::

    python migration-harness/generate_sobol_tables.py

Idempotent: re-running against the same C++ checkout reproduces byte-identical
output, so the generated resources can be diffed against a fresh run to prove
they were not hand-edited.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CPP = REPO / "migration-harness" / "cpp" / "quantlib" / "ql" / "math" / "randomnumbers"
OUT = REPO / "pquantlib" / "src" / "pquantlib" / "math" / "randomnumbers" / "data"

_NUM = re.compile(r"-?\d+")


def _strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    return re.sub(r"//[^\n]*", " ", text)


_DECL = re.compile(r"(\w+)\s*\[[^\]]*\]\s*=?\s*\{")


def index_arrays(text: str) -> dict[str, str]:
    """Map every ``NAME[...] = { ... }`` in ``text`` to its brace body.

    Single linear pass — sobolrsg.cpp declares ~237 000 arrays, so a fresh
    ``re.search`` per lookup would be quadratic and take hours.
    """
    out: dict[str, str] = {}
    for m in _DECL.finditer(text):
        start = m.end()
        depth = 1
        i = start
        while depth:
            c = text[i]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
            i += 1
        out[m.group(1)] = text[start : i - 1]
    return out


def _numbers(body: str) -> list[int]:
    return [int(t) for t in _NUM.findall(body)]


def _write_rows(path: Path, rows: list[list[int]], header: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write(f"# {header}\n")
        f.write("# Generated by migration-harness/generate_sobol_tables.py — do not edit.\n")
        for row in rows:
            f.write(" ".join(str(v) for v in row))
            f.write("\n")
    print(f"  {path.relative_to(REPO)}: {len(rows)} rows, {path.stat().st_size} bytes")


# --------------------------------------------------------------- polynomials


def _primitive_polynomials(
    arrays: dict[str, str], prefix: str, degrees: int
) -> list[list[int]]:
    """Rows of primitive polynomials by degree, ``-1`` terminator dropped."""
    rows: list[list[int]] = []
    for d in range(1, degrees + 1):
        vals = _numbers(arrays[f"{prefix}{d:02d}"])
        assert vals[-1] == -1, (prefix, d, vals[-5:])
        rows.append(vals[:-1])
    return rows


# ------------------------------------------------------- direction integers


def _initializer_rows(arrays: dict[str, str], pointer_table: str) -> list[list[int]]:
    """Rows of free direction integers, ``0`` terminator dropped.

    ``pointer_table`` is the C++ ``const std::uint32_t * const NAME[n]`` array;
    its entries name the per-dimension arrays in order (dimension 2 upwards).
    """
    names = re.findall(r"[A-Za-z_]\w*", arrays[pointer_table])
    rows: list[list[int]] = []
    for name in names:
        vals = _numbers(arrays[name])
        assert vals[-1] == 0, (name, vals[-5:])
        rows.append(vals[:-1])
    return rows


def main() -> int:
    print("reading C++ sources...")
    pp_arrays = index_arrays(
        _strip_comments((CPP / "primitivepolynomials.cpp").read_text(encoding="latin-1"))
    )
    sobol_arrays = index_arrays(
        _strip_comments((CPP / "sobolrsg.cpp").read_text(encoding="latin-1"))
    )
    lattice_arrays = index_arrays(
        _strip_comments((CPP / "latticerules.cpp").read_text(encoding="latin-1"))
    )

    print("primitive polynomials...")
    _write_rows(
        OUT / "sobol_primitive_polynomials.txt",
        _primitive_polynomials(pp_arrays, "PrimitivePolynomialDegree", 18),
        "PrimitivePolynomials[degree-1][*] — primitivepolynomials.cpp (v1.43)",
    )
    _write_rows(
        OUT / "sobol_alt_primitive_polynomials.txt",
        _primitive_polynomials(sobol_arrays, "AltPrimitivePolynomialDegree", 8),
        "AltPrimitivePolynomials[degree-1][*] — sobolrsg.cpp (v1.43)",
    )

    print("direction integers...")
    families = {
        "jaeckel": "initializers",
        "sobol_levitan": "SLinitializers",
        "lemieux": "Linitializers",
        "joe_kuo_d5": "JoeKuoD5initializers",
        "joe_kuo_d6": "JoeKuoD6initializers",
        "joe_kuo_d7": "JoeKuoD7initializers",
        "kuo": "Kuoinitializers",
        "kuo2": "Kuo2initializers",
        "kuo3": "Kuo3initializers",
    }
    for key, table in families.items():
        _write_rows(
            OUT / f"sobol_init_{key}.txt",
            _initializer_rows(sobol_arrays, table),
            f"{table}[dim-2][*] — sobolrsg.cpp (v1.43)",
        )

    print("lattice rules...")
    for letter in "ABCD":
        vals = _numbers(lattice_arrays[f"lattice{letter}"])
        assert len(vals) == 3600, (letter, len(vals))
        _write_rows(
            OUT / f"lattice_rule_{letter.lower()}.txt",
            [vals],
            f"latticeRule {letter} generating vector — latticerules.cpp (v1.43)",
        )

    print("done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
