"""OneFactorCopula — abstract base + Gaussian + Student concrete subclasses.

# C++ parity: ql/experimental/credit/onefactorcopula.{hpp,cpp},
# onefactorgaussiancopula.{hpp,cpp}, onefactorstudentcopula.{hpp,cpp}
# @ v1.42.1 (099987f0).

The one-factor copula

    Y_i = a_i M + sqrt(1 - a_i^2) Z_i

models joint defaults via a common factor ``M`` and idiosyncratic factors
``Z_i``. Given a per-name unconditional default probability ``p``, the
*conditional* probability given a realization ``m`` of M is

    p_hat(p, m) = F_Z((F_Y^-1(p) - sqrt(rho) * m) / sqrt(1 - rho))

where ``rho`` is the squared common-factor loading (``a_i^2``). This is the
mechanism used by ``GaussianLHPLossModel`` (Vasicek 2002 LHP closed form),
the binomial / recursive / saddlepoint loss models, and the latent-model
hierarchy.

The C++ ``OneFactorCopula`` is a ``LazyObject`` because it pre-tabulates
the cumulative distribution of Y for the Student-copula path. The Gaussian
copula overrides ``cumulativeY``/``inverseCumulativeY`` with closed-form
identities and so does not need the table. The Python port keeps the same
two-step structure: ``OneFactorCopula`` is the LazyObject with the Euler
integration helpers; ``OneFactorGaussianCopula`` is the closed-form
override; ``OneFactorStudentCopula`` rebuilds the table on
``_perform_calculations``.
"""

from __future__ import annotations

import bisect
from abc import abstractmethod
from collections.abc import Callable
from typing import Final

import numpy as np
import numpy.typing as npt

from pquantlib import qassert
from pquantlib.math.distributions.cumulative_normal_distribution import (
    CumulativeNormalDistribution,
)
from pquantlib.math.distributions.inverse_cumulative_normal import (
    InverseCumulativeNormal,
)
from pquantlib.math.distributions.normal_distribution import NormalDistribution
from pquantlib.math.distributions.student_t_distribution import (
    CumulativeStudentDistribution,
    StudentDistribution,
)
from pquantlib.patterns.lazy_object import LazyObject

# --- the C++ cumulativeYintegral quadrature constants -----------------------
# All three Student-flavoured copulas hard-code the same numbers inside
# ``cumulativeYintegral`` (onefactorstudentcopula.cpp:79-83, 161-163, 244-246),
# independently of the ``maximum`` / ``integrationSteps`` ctor arguments.
_YI_MINIMUM: Final[float] = -10.0
_YI_MAXIMUM: Final[float] = 10.0
_YI_STEPS: Final[int] = 400
# ... and the same numbers again inside ``performCalculations`` for the y grid
# (onefactorstudentcopula.cpp:51-53, 133-135, 215-217).
_TABLE_YMIN: Final[float] = -10.0
_TABLE_YMAX: Final[float] = 10.0
_TABLE_STEPS: Final[int] = 200

# The INNER loop of cumulativeYintegral is bounded by
# ``(y - sqrt(c) m) / sqrt(1 - c)`` (or its mirror), NOT by ``maximum``. With
# |y| <= 10 and |m| < 10 that bound peaks just above 24 at c = 1/2, so the
# grid has to run well past ``maximum``. 100 leaves a wide margin and is
# checked at runtime.
_INNER_CAP: Final[float] = 100.0


def _euler_grid(minimum: float, cap: float, delta: float) -> list[float]:
    """Reproduce ``for (Real v = minimum + delta/2; v < cap; v += delta)``.

    # C++ parity note: the grid is generated by *repeated addition*, not by
    # ``minimum + delta/2 + i*delta``. The two differ in the last bits once
    # ``delta`` is not exactly representable, and every term of the C++
    # Riemann sum is evaluated at the accumulated value. Reproducing the
    # accumulation is the only way to land on the same doubles.
    """
    out: list[float] = []
    v = minimum + delta / 2.0
    while v < cap:
        out.append(v)
        v += delta
    return out


class OneFactorCopula(LazyObject):
    """Abstract base for one-factor copula models.

    Subclasses must implement ``density(m)`` and ``cumulative_z(z)`` and
    may override ``cumulative_y`` / ``inverse_cumulative_y`` if a
    closed form is available; otherwise the base class uses the
    Euler-integration table built by ``_perform_calculations``.

    # C++ parity: onefactorcopula.hpp:102.
    """

    __slots__ = ("_correlation", "_cumulative_y_tab", "_max", "_min", "_steps", "_y_tab")

    def __init__(
        self,
        correlation: float,
        maximum: float = 5.0,
        integration_steps: int = 50,
        minimum: float = -5.0,
    ) -> None:
        super().__init__()
        qassert.require(
            -1.0 <= correlation <= 1.0,
            f"correlation out of range [-1, +1]: {correlation}",
        )
        self._correlation = correlation
        self._max = maximum
        self._steps = integration_steps
        self._min = minimum
        self._y_tab: list[float] = []
        self._cumulative_y_tab: list[float] = []

    def correlation(self) -> float:
        """Single correlation parameter."""
        self.calculate()
        return self._correlation

    def set_correlation(self, correlation: float) -> None:
        """Mutate the correlation (Quote-equivalent path).

        # C++ parity divergence: the C++ class stores a ``Handle<Quote>``
        # for the correlation. Python uses a direct setter; rho mutation
        # invalidates the cache so the Student-copula table is rebuilt.
        """
        qassert.require(
            -1.0 <= correlation <= 1.0,
            f"correlation out of range [-1, +1]: {correlation}",
        )
        self._correlation = correlation
        self.update()

    @abstractmethod
    def density(self, m: float) -> float:
        """Density function of M (zero mean, unit variance)."""

    @abstractmethod
    def cumulative_z(self, z: float) -> float:
        """Cumulative distribution function of Z (zero mean, unit variance)."""

    # --- Default implementations using the tabulated Y distribution ---

    def cumulative_y(self, y: float) -> float:
        """Cumulative distribution of Y.

        Default: linear interpolation on the tabulated ``_y_tab`` /
        ``_cumulative_y_tab`` arrays. Subclasses may override with a
        closed form.

        # C++ parity: onefactorcopula.cpp:57-75.
        """
        self.calculate()
        qassert.require(len(self._y_tab) > 0, "cumulative Y not tabulated yet")

        if y < self._y_tab[0]:
            return self._cumulative_y_tab[0]
        for i in range(1, len(self._y_tab)):
            if self._y_tab[i] > y:
                return (
                    (self._y_tab[i] - y) * self._cumulative_y_tab[i - 1]
                    + (y - self._y_tab[i - 1]) * self._cumulative_y_tab[i]
                ) / (self._y_tab[i] - self._y_tab[i - 1])
        return self._cumulative_y_tab[-1]

    def inverse_cumulative_y(self, x: float) -> float:
        """Inverse cumulative distribution of Y.

        Default: linear interpolation on the tabulated arrays.

        # C++ parity: onefactorcopula.cpp:78-96.
        """
        self.calculate()
        qassert.require(len(self._y_tab) > 0, "cumulative Y not tabulated yet")

        if x < self._cumulative_y_tab[0]:
            return self._y_tab[0]
        for i in range(1, len(self._cumulative_y_tab)):
            if self._cumulative_y_tab[i] > x:
                return (
                    (self._cumulative_y_tab[i] - x) * self._y_tab[i - 1]
                    + (x - self._cumulative_y_tab[i - 1]) * self._y_tab[i]
                ) / (self._cumulative_y_tab[i] - self._cumulative_y_tab[i - 1])
        return self._y_tab[-1]

    def _perform_calculations(self) -> None:
        """No-op by default — Gaussian copula needs no table.

        Student copula overrides this to rebuild ``_y_tab`` and
        ``_cumulative_y_tab`` over [-max, max] when correlation changes.
        """
        # default no-op

    # --- Euler integration helpers over M ---

    def steps(self) -> int:
        return self._steps

    def dm(self) -> float:
        # # C++ parity: onefactorcopula.hpp:272.
        return (self._max - self._min) / self._steps

    def m(self, i: int) -> float:
        # # C++ parity: onefactorcopula.hpp:276.
        qassert.require(i < self._steps, f"index out of range: {i}")
        return self._min + self.dm() * i + self.dm() / 2.0

    def density_dm(self, i: int) -> float:
        # # C++ parity: onefactorcopula.hpp:281.
        qassert.require(i < self._steps, f"index out of range: {i}")
        return self.density(self.m(i)) * self.dm()

    # --- Conditional default probability ---

    def conditional_probability(self, prob: float, m: float) -> float:
        """p_hat(m) = F_Z((F_Y^-1(p) - sqrt(rho) m) / sqrt(1-rho)).

        # C++ parity: onefactorcopula.cpp:27-42.
        """
        self.calculate()
        # FIXME (mirrors C++ guard at onefactorcopula.cpp:31)
        if prob < 1e-10:
            return 0.0

        c = self._correlation
        res = self.cumulative_z(
            (self.inverse_cumulative_y(prob) - np.sqrt(c) * m) / np.sqrt(1.0 - c)
        )
        qassert.require(
            0.0 <= res <= 1.0,
            f"conditional probability {res} out of range",
        )
        return res

    def conditional_probability_vec(
        self, probs: list[float], m: float
    ) -> list[float]:
        """Vector overload of ``conditional_probability``.

        # C++ parity: onefactorcopula.cpp:44-54.
        """
        self.calculate()
        return [self.conditional_probability(p, m) for p in probs]

    def integral(self, p: float) -> float:
        """Integral over rho_M(m) of the conditional probability.

        # C++ parity: onefactorcopula.hpp:169 — Euler integration over M.
        """
        qassert.require(
            0.0 <= p <= 1.0, f"probability p={p} out of range [0,1]"
        )
        self.calculate()
        avg = 0.0
        for k in range(self.steps()):
            pp = self.conditional_probability(p, self.m(k))
            avg += pp * self.density_dm(k)
        return avg

    def integral_fn(
        self,
        f: Callable[[list[float]], float],
        probabilities: list[float],
    ) -> float:
        """Integral over rho_M(m) of f(conditional probabilities vector).

        Mirrors the templated ``integral`` at onefactorcopula.hpp:193 but
        takes any callable ``f(list[float]) -> float`` as Python duck-types
        the C++ template.
        """
        self.calculate()
        avg: float = 0.0
        for i in range(self._steps):
            conditional = self.conditional_probability_vec(probabilities, self.m(i))
            avg += f(conditional) * self.density_dm(i)
        return avg

    def check_moments(self, tolerance: float = 1e-2) -> int:
        """Check (norm=1, mean=0, var=1) for M, Z, Y up to ``tolerance``.

        # C++ parity: onefactorcopula.cpp:99-157. Returns 0 on success;
        # raises on tolerance violation. The default tolerance is loosened
        # from the C++ default because Euler integration over 50 steps
        # only achieves ~1e-2 accuracy.
        """
        self.calculate()
        norm = 0.0
        mean = 0.0
        var = 0.0
        for i in range(self.steps()):
            norm += self.density_dm(i)
            mean += self.m(i) * self.density_dm(i)
            var += self.m(i) ** 2 * self.density_dm(i)
        qassert.require(abs(norm - 1.0) < tolerance, f"M norm {norm} out of tolerance")
        qassert.require(abs(mean) < tolerance, f"M mean {mean} out of tolerance")
        qassert.require(
            abs(var - 1.0) < tolerance, f"M variance {var} out of tolerance"
        )
        return 0


class OneFactorGaussianCopula(OneFactorCopula):
    """One-factor Gaussian copula.

    All three of M, Z, Y are standard normal so cumulative_y is the same
    standard CDF as cumulative_z — no table needed.

    # C++ parity: onefactorgaussiancopula.{hpp,cpp}.
    """

    __slots__ = ("_cumulative", "_density", "_inv_cumulative")

    def __init__(
        self,
        correlation: float,
        maximum: float = 5.0,
        integration_steps: int = 50,
    ) -> None:
        super().__init__(correlation, maximum, integration_steps)
        self._density = NormalDistribution()
        self._cumulative = CumulativeNormalDistribution()
        self._inv_cumulative = InverseCumulativeNormal()

    def density(self, m: float) -> float:
        # # C++ parity: onefactorgaussiancopula.hpp:64.
        return self._density(m)

    def cumulative_z(self, z: float) -> float:
        # # C++ parity: onefactorgaussiancopula.hpp:68.
        return self._cumulative(z)

    def cumulative_y(self, y: float) -> float:
        # # C++ parity: onefactorgaussiancopula.hpp:72.
        return self._cumulative(y)

    def inverse_cumulative_y(self, x: float) -> float:
        # # C++ parity: onefactorgaussiancopula.hpp:76.
        return InverseCumulativeNormal.standard_value(x)

    def _perform_calculations(self) -> None:
        # # C++ parity: onefactorgaussiancopula.hpp:57 — nothing to do.
        return None


class _TabulatedYCopula(OneFactorCopula):
    """Shared machinery for the three Student-flavoured copulas.

    # C++ parity: the ``performCalculations`` / ``cumulativeYintegral`` pair
    # is written out three times, once per class, in
    # onefactorstudentcopula.cpp — identical except for which density plays
    # the M role and which the Z role. Python factors the common body here;
    # subclasses supply the two density expressions, the post-multiplication
    # divisor and the two degenerate-correlation closed forms.

    # C++ parity note: ``performCalculations`` ignores ``max_`` / ``steps_``
    # entirely and always tabulates 201 points over [-10, +10]; likewise
    # ``cumulativeYintegral`` always integrates 400x400 over [-10, +10]. Only
    # ``density``/``integral``/``densitydm`` see the ctor's ``maximum`` and
    # ``integrationSteps`` (and the base ctor's ``minimum = -5``, which the
    # Student ctors never override — so the M grid really is asymmetric).
    """

    __slots__ = (
        "_a_vals",
        "_b_vals",
        "_inner_grid",
        "_inner_grid_np",
        "_n_outer",
        "_post_divisor",
    )

    def _setup_quadrature(self, post_divisor: float | None) -> None:
        """Precompute the shared Euler grids and the two density vectors."""
        delta = (_YI_MAXIMUM - _YI_MINIMUM) / _YI_STEPS
        grid = _euler_grid(_YI_MINIMUM, _INNER_CAP, delta)
        self._inner_grid: list[float] = grid
        self._inner_grid_np: npt.NDArray[np.float64] = np.asarray(grid, dtype=np.float64)
        # The outer loop stops at ``maximum``; the outer grid is therefore a
        # prefix of the inner one (same start, same accumulation).
        self._n_outer: int = bisect.bisect_left(grid, _YI_MAXIMUM)
        self._a_vals: npt.NDArray[np.float64] = np.asarray(
            [self._m_factor(v) for v in grid], dtype=np.float64
        )
        self._b_vals: npt.NDArray[np.float64] = np.asarray(
            [self._z_factor(v) for v in grid], dtype=np.float64
        )
        self._post_divisor: float | None = post_divisor

    # --- subclass hooks ----------------------------------------------------

    @abstractmethod
    def _m_factor(self, m: float) -> float:
        """The C++ sub-expression standing for the M density in the sum."""

    @abstractmethod
    def _z_factor(self, z: float) -> float:
        """The C++ sub-expression standing for the Z density in the sum."""

    @abstractmethod
    def _cumulative_y_at_zero_correlation(self, y: float) -> float:
        """Closed form taken by ``cumulativeYintegral`` when c == 0."""

    @abstractmethod
    def _cumulative_y_at_unit_correlation(self, y: float) -> float:
        """Closed form taken by ``cumulativeYintegral`` when c == 1."""

    # --- the quadrature ----------------------------------------------------

    def cumulative_y_integral(self, y: float) -> float:
        """Riemann sum for F_Y(y) over the (m, z) plane.

        # C++ parity: onefactorstudentcopula.cpp:63-106 (and the two
        # verbatim copies at :145-188 and :227-271).
        """
        c = self._correlation
        if c == 0.0:
            return self._cumulative_y_at_zero_correlation(y)
        if c == 1.0:
            return self._cumulative_y_at_unit_correlation(y)

        delta = (_YI_MAXIMUM - _YI_MINIMUM) / _YI_STEPS
        outer = self._inner_grid_np[: self._n_outer]
        inner = self._inner_grid_np

        if c < 0.5:
            # outer over m, inner over z bounded by (y - sqrt(c) m)/sqrt(1-c)
            bounds = (y - np.sqrt(c) * outer) / np.sqrt(1.0 - c)
            outer_is_m = True
        else:
            # outer over z, inner over m bounded by (y - sqrt(1-c) z)/sqrt(c)
            bounds = (y - np.sqrt(1.0 - c) * outer) / np.sqrt(c)
            outer_is_m = False

        qassert.require(
            bool(np.all(bounds < _INNER_CAP)),
            f"inner Euler grid too short for y={y}, c={c}",
        )
        counts: npt.NDArray[np.int64] = np.asarray(
            np.searchsorted(inner, bounds, side="left"), dtype=np.int64
        )
        total = int(counts.sum())
        if total == 0:
            return 0.0

        outer_idx = np.repeat(np.arange(counts.size, dtype=np.int64), counts)
        starts = np.repeat(np.cumsum(counts) - counts, counts)
        inner_idx = np.arange(total, dtype=np.int64) - starts

        if outer_is_m:
            flat = self._a_vals[outer_idx] * self._b_vals[inner_idx]
        else:
            flat = self._a_vals[inner_idx] * self._b_vals[outer_idx]
        if self._post_divisor is not None:
            flat = flat / self._post_divisor

        # C++ accumulates into a single running total in (outer, inner)
        # order. ``np.cumsum`` is the only numpy reduction that keeps that
        # order; ``np.sum`` uses pairwise summation and would round
        # differently.
        cumulated = float(np.cumsum(flat)[-1])
        return cumulated * delta * delta

    def _perform_calculations(self) -> None:
        """Tabulate F_Y over 201 points of [-10, +10].

        # C++ parity: onefactorstudentcopula.cpp:43-60.
        """
        y_tab: list[float] = []
        cum_tab: list[float] = []
        for i in range(_TABLE_STEPS + 1):
            y = _TABLE_YMIN + (_TABLE_YMAX - _TABLE_YMIN) * i / _TABLE_STEPS
            y_tab.append(y)
            cum_tab.append(self.cumulative_y_integral(y))
        self._y_tab = y_tab
        self._cumulative_y_tab = cum_tab


class OneFactorStudentCopula(_TabulatedYCopula):
    """One-factor (double) Student-t copula.

    Both M and Z are Student-t distributed with ``nm`` and ``nz`` degrees of
    freedom, scaled to unit variance. Y has no closed form so its CDF is
    tabulated by a 400x400 Euler integration of the convolution defining F_Y.

    # C++ parity: ql/experimental/credit/onefactorstudentcopula.hpp:53-86,
    # .cpp:25-106 (v1.43).
    """

    __slots__ = ("_cumulative", "_density", "_nm", "_nz", "_scale_m", "_scale_z")

    def __init__(
        self,
        correlation: float,
        nz: int,
        nm: int,
        maximum: float = 10.0,
        integration_steps: int = 200,
    ) -> None:
        qassert.require(nz > 2, f"nz must be > 2 for finite variance: {nz}")
        qassert.require(nm > 2, f"nm must be > 2 for finite variance: {nm}")
        super().__init__(correlation, maximum, integration_steps)
        self._nz = nz
        self._nm = nm
        self._density = StudentDistribution(nm)
        self._cumulative = CumulativeStudentDistribution(nz)
        # Variance of Student-t(nu) is nu/(nu-2); scale to unit variance.
        # # C++ parity: onefactorstudentcopula.cpp:36-37.
        self._scale_m: float = float(np.sqrt((nm - 2.0) / nm))
        self._scale_z: float = float(np.sqrt((nz - 2.0) / nz))
        self._setup_quadrature(post_divisor=self._scale_z)

    def density(self, m: float) -> float:
        # # C++ parity: onefactorstudentcopula.hpp:80-82.
        return self._density(m / self._scale_m) / self._scale_m

    def cumulative_z(self, z: float) -> float:
        # # C++ parity: onefactorstudentcopula.hpp:84-86.
        return self._cumulative(z / self._scale_z)

    # --- quadrature hooks --------------------------------------------------

    def _m_factor(self, m: float) -> float:
        # C++ writes ``dm (m / scaleM_) / scaleM_ * dz (z / scaleZ_) / scaleZ_``
        # which associates as ``((dm(..)/scaleM * dz(..)) / scaleZ)``.
        return StudentDistribution(self._nm)(m / self._scale_m) / self._scale_m

    def _z_factor(self, z: float) -> float:
        return StudentDistribution(self._nz)(z / self._scale_z)

    def _cumulative_y_at_zero_correlation(self, y: float) -> float:
        # # C++ parity: onefactorstudentcopula.cpp:67-68.
        return CumulativeStudentDistribution(self._nz)(y / self._scale_z)

    def _cumulative_y_at_unit_correlation(self, y: float) -> float:
        # # C++ parity: onefactorstudentcopula.cpp:70-71.
        return CumulativeStudentDistribution(self._nm)(y / self._scale_m)


class OneFactorGaussianStudentCopula(_TabulatedYCopula):
    """One-factor Gaussian-Student t-copula: Gaussian M, Student-t Z.

    # C++ parity: ql/experimental/credit/onefactorstudentcopula.hpp:108-140,
    # .cpp:109-188 (v1.43).

    Only ``Z`` needs rescaling (``sqrt((nz - 2) / nz)``); ``M`` is already a
    standard normal.
    """

    __slots__ = ("_cumulative", "_density", "_nz", "_scale_z")

    def __init__(
        self,
        correlation: float,
        nz: int,
        maximum: float = 10.0,
        integration_steps: int = 200,
    ) -> None:
        qassert.require(nz > 2, f"degrees of freedom must be > 2: {nz}")
        super().__init__(correlation, maximum, integration_steps)
        self._nz = nz
        self._density = NormalDistribution()
        self._cumulative = CumulativeStudentDistribution(nz)
        # # C++ parity: onefactorstudentcopula.cpp:119.
        self._scale_z: float = float(np.sqrt((nz - 2.0) / nz))
        self._setup_quadrature(post_divisor=self._scale_z)

    def density(self, m: float) -> float:
        # # C++ parity: onefactorstudentcopula.hpp:134-136.
        return self._density(m)

    def cumulative_z(self, z: float) -> float:
        # # C++ parity: onefactorstudentcopula.hpp:138-140.
        return self._cumulative(z / self._scale_z)

    # --- quadrature hooks --------------------------------------------------

    def _m_factor(self, m: float) -> float:
        # C++ writes ``dm (m) * dz (z / scaleZ_) / scaleZ_``.
        return NormalDistribution()(m)

    def _z_factor(self, z: float) -> float:
        return StudentDistribution(self._nz)(z / self._scale_z)

    def _cumulative_y_at_zero_correlation(self, y: float) -> float:
        # # C++ parity: onefactorstudentcopula.cpp:149-150.
        return CumulativeStudentDistribution(self._nz)(y / self._scale_z)

    def _cumulative_y_at_unit_correlation(self, y: float) -> float:
        # # C++ parity: onefactorstudentcopula.cpp:152-153.
        return CumulativeNormalDistribution()(y)


class OneFactorStudentGaussianCopula(_TabulatedYCopula):
    """One-factor Student t-Gaussian copula: Student-t M, Gaussian Z.

    # C++ parity: ql/experimental/credit/onefactorstudentcopula.hpp:161-193,
    # .cpp:191-271 (v1.43).

    Only ``M`` needs rescaling (``sqrt((nm - 2) / nm)``); ``Z`` is already a
    standard normal.
    """

    __slots__ = ("_cumulative", "_density", "_nm", "_scale_m")

    def __init__(
        self,
        correlation: float,
        nm: int,
        maximum: float = 10.0,
        integration_steps: int = 200,
    ) -> None:
        qassert.require(nm > 2, f"degrees of freedom must be > 2: {nm}")
        super().__init__(correlation, maximum, integration_steps)
        self._nm = nm
        self._density = StudentDistribution(nm)
        self._cumulative = CumulativeNormalDistribution()
        # # C++ parity: onefactorstudentcopula.cpp:201.
        self._scale_m: float = float(np.sqrt((nm - 2.0) / nm))
        self._setup_quadrature(post_divisor=None)

    def density(self, m: float) -> float:
        # # C++ parity: onefactorstudentcopula.hpp:187-189.
        return self._density(m / self._scale_m) / self._scale_m

    def cumulative_z(self, z: float) -> float:
        # # C++ parity: onefactorstudentcopula.hpp:191-193.
        return self._cumulative(z)

    # --- quadrature hooks --------------------------------------------------

    def _m_factor(self, m: float) -> float:
        # C++ writes ``dm (m / scaleM_) / scaleM_ * dz (z)`` — no trailing
        # division, hence ``post_divisor=None``.
        return StudentDistribution(self._nm)(m / self._scale_m) / self._scale_m

    def _z_factor(self, z: float) -> float:
        return NormalDistribution()(z)

    def _cumulative_y_at_zero_correlation(self, y: float) -> float:
        # # C++ parity: onefactorstudentcopula.cpp:231-232.
        return CumulativeNormalDistribution()(y)

    def _cumulative_y_at_unit_correlation(self, y: float) -> float:
        # # C++ parity: onefactorstudentcopula.cpp:234-235.
        return CumulativeStudentDistribution(self._nm)(y / self._scale_m)


__all__ = [
    "OneFactorCopula",
    "OneFactorGaussianCopula",
    "OneFactorGaussianStudentCopula",
    "OneFactorStudentCopula",
    "OneFactorStudentGaussianCopula",
]
