"""Tests for VanillaSwap + DiscountingSwapEngine cross-validated vs the C++ probe.

Reference values: ``migration-harness/references/cluster/l3c.json``.
Generated by ``migration-harness/cpp/probes/cluster_l3c/probe.cpp``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import cast

import pytest

from pquantlib.daycounters.actual_360 import Actual360
from pquantlib.daycounters.thirty_360 import Convention, Thirty360
from pquantlib.indexes.ibor.euribor import Euribor
from pquantlib.instruments.swap import SwapType
from pquantlib.instruments.vanilla_swap import VanillaSwap
from pquantlib.pricingengines.swap.discounting_swap_engine import DiscountingSwapEngine
from pquantlib.termstructures.protocols import YieldTermStructureProtocol
from pquantlib.termstructures.yield_.flat_forward import FlatForward
from pquantlib.testing import tolerance
from pquantlib.time.business_day_convention import BusinessDayConvention
from pquantlib.time.calendars.target import TARGET
from pquantlib.time.compounding import Compounding
from pquantlib.time.date import Date
from pquantlib.time.date_generation import DateGeneration
from pquantlib.time.frequency import Frequency
from pquantlib.time.month import Month
from pquantlib.time.period import Period
from pquantlib.time.schedule import Schedule
from pquantlib.time.time_unit import TimeUnit

_REF_PATH = Path(__file__).resolve().parents[3] / "migration-harness/references/cluster/l3c.json"


@pytest.fixture(scope="module")
def cluster_refs() -> dict[str, dict[str, float]]:
    return json.loads(_REF_PATH.read_text())


def _five_year_vanilla_swap(
    fixed_rate: float, swap_type: SwapType = SwapType.Payer
) -> tuple[VanillaSwap, YieldTermStructureProtocol, Date]:
    """Build the 5y vanilla swap used by the C++ probe.

    Settings: eval_date = 17 Jan 2024 (Wed), 1M EUR notional, semi-annual
    fixed leg vs quarterly Euribor3M, FlatForward(5%) curve.
    """
    eval_date = Date.from_ymd(17, Month.January, 2024)
    curve = cast(
        YieldTermStructureProtocol,
        FlatForward.from_rate(
            eval_date, 0.05, Actual360(), Compounding.Continuous, Frequency.Annual
        ),
    )
    idx = Euribor(Period(3, TimeUnit.Months), curve)

    cal = TARGET()
    settle = cal.advance(eval_date, 2, TimeUnit.Days)
    end = settle + Period(5, TimeUnit.Years)

    fixed_sched = Schedule.from_rule(
        settle, end, Period(6, TimeUnit.Months), cal,
        BusinessDayConvention.ModifiedFollowing,
        BusinessDayConvention.ModifiedFollowing,
        DateGeneration.Backward, False,
    )
    float_sched = Schedule.from_rule(
        settle, end, Period(3, TimeUnit.Months), cal,
        BusinessDayConvention.ModifiedFollowing,
        BusinessDayConvention.ModifiedFollowing,
        DateGeneration.Backward, False,
    )
    swap = VanillaSwap(
        swap_type, 1_000_000.0,
        fixed_sched, fixed_rate, Thirty360(Convention.BondBasis),
        float_sched, idx, 0.0, idx.day_counter(),
    )
    swap.set_pricing_engine(DiscountingSwapEngine(curve))
    return swap, curve, settle


# --- Schedule sanity -----------------------------------------------------


def test_vanilla_swap_leg_sizes(cluster_refs: dict[str, dict[str, float]]) -> None:
    """Per probe: 5y semi-annual = 10 fixed periods; quarterly = 20 float periods."""
    swap, _, _ = _five_year_vanilla_swap(0.05)
    expected = cluster_refs["vanilla_swap_5y"]
    assert len(swap.fixed_leg()) == expected["fixed_leg_size"]
    assert len(swap.floating_leg()) == expected["floating_leg_size"]


# --- NPV / fair_rate / fixed-leg NPV / BPS -------------------------------


def test_vanilla_swap_npv_matches_probe(cluster_refs: dict[str, dict[str, float]]) -> None:
    swap, _, _ = _five_year_vanilla_swap(0.05)
    expected = cluster_refs["vanilla_swap_5y"]
    # LOOSE tier: NPV chain depends on Schedule + leg-iteration + IBOR forecast;
    # accumulates lots of floating-point work where any small idiom drift
    # could push past TIGHT. 1e-8 abs/rel covers genuine equivalence.
    tolerance.loose(swap.npv(), expected["npv"])


def test_vanilla_swap_fixed_leg_npv(cluster_refs: dict[str, dict[str, float]]) -> None:
    swap, _, _ = _five_year_vanilla_swap(0.05)
    expected = cluster_refs["vanilla_swap_5y"]
    tolerance.loose(swap.fixed_leg_npv(), expected["fixed_leg_npv"])


def test_vanilla_swap_floating_leg_npv(cluster_refs: dict[str, dict[str, float]]) -> None:
    swap, _, _ = _five_year_vanilla_swap(0.05)
    expected = cluster_refs["vanilla_swap_5y"]
    tolerance.loose(swap.floating_leg_npv(), expected["floating_leg_npv"])


def test_vanilla_swap_fixed_leg_bps(cluster_refs: dict[str, dict[str, float]]) -> None:
    swap, _, _ = _five_year_vanilla_swap(0.05)
    expected = cluster_refs["vanilla_swap_5y"]
    tolerance.loose(swap.fixed_leg_bps(), expected["fixed_leg_bps"])


def test_vanilla_swap_floating_leg_bps(cluster_refs: dict[str, dict[str, float]]) -> None:
    swap, _, _ = _five_year_vanilla_swap(0.05)
    expected = cluster_refs["vanilla_swap_5y"]
    tolerance.loose(swap.floating_leg_bps(), expected["floating_leg_bps"])


def test_vanilla_swap_fair_rate(cluster_refs: dict[str, dict[str, float]]) -> None:
    swap, _, _ = _five_year_vanilla_swap(0.05)
    expected = cluster_refs["vanilla_swap_5y"]
    # LOOSE: fair_rate derives from NPV / (BPS / basisPoint).
    tolerance.loose(swap.fair_rate(), expected["fair_rate"])


def test_vanilla_swap_fair_spread(cluster_refs: dict[str, dict[str, float]]) -> None:
    swap, _, _ = _five_year_vanilla_swap(0.05)
    expected = cluster_refs["vanilla_swap_5y"]
    tolerance.loose(swap.fair_spread(), expected["fair_spread"])


# --- Receiver variant ----------------------------------------------------


def test_vanilla_swap_receiver_flips_npv_sign(cluster_refs: dict[str, dict[str, float]]) -> None:
    swap, _, _ = _five_year_vanilla_swap(0.06, swap_type=SwapType.Receiver)
    expected = cluster_refs["vanilla_swap_receiver_6pct"]
    tolerance.loose(swap.npv(), expected["npv"])
    # The fair_rate stays roughly 5.14% — receiver/payer don't change it
    # since both swaps look at the same fixed/float break-even.
    tolerance.loose(swap.fair_rate(), expected["fair_rate"])


# --- Direct ctor inspectors ----------------------------------------------


def test_vanilla_swap_inspectors() -> None:
    swap, curve, settle = _five_year_vanilla_swap(0.05)
    assert swap.swap_type() == SwapType.Payer
    assert swap.nominal() == 1_000_000.0
    assert swap.fixed_rate() == 0.05
    assert swap.spread() == 0.0
    assert swap.payer(0)  # fixed leg paid
    assert not swap.payer(1)  # floating leg received
    # Schedule end ≈ settle + 5y; payment-cal advances make it exact.
    assert swap.maturity_date() > settle
    _ = curve  # silence unused-var
