"""BlackCapFloorEngine + BachelierCapFloorEngine cross-validation vs C++ probe.

Reference values: ``migration-harness/references/cluster/l4e.json``
generated by ``migration-harness/cpp/probes/cluster_l4e/probe.cpp``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import cast

import pytest

from pquantlib.cashflows.cash_flow import CashFlow
from pquantlib.cashflows.coupon_pricer import IborCouponPricer, set_coupon_pricer
from pquantlib.cashflows.ibor_leg import ibor_leg
from pquantlib.daycounters.actual_360 import Actual360
from pquantlib.indexes.ibor.euribor import Euribor
from pquantlib.instruments.cap_floor import Cap, Floor
from pquantlib.pricingengines.capfloor.bachelier_capfloor_engine import (
    BachelierCapFloorEngine,
)
from pquantlib.pricingengines.capfloor.black_capfloor_engine import BlackCapFloorEngine
from pquantlib.termstructures.protocols import YieldTermStructureProtocol
from pquantlib.termstructures.yield_.flat_forward import FlatForward
from pquantlib.testing import tolerance
from pquantlib.time.business_day_convention import BusinessDayConvention
from pquantlib.time.calendars.target import TARGET
from pquantlib.time.compounding import Compounding
from pquantlib.time.date import Date
from pquantlib.time.date_generation import DateGeneration
from pquantlib.time.frequency import Frequency
from pquantlib.time.month import Month
from pquantlib.time.period import Period
from pquantlib.time.schedule import Schedule
from pquantlib.time.time_unit import TimeUnit

_REF_PATH = (
    Path(__file__).resolve().parents[4] / "migration-harness/references/cluster/l4e.json"
)


@pytest.fixture(scope="module")
def cluster_refs() -> dict[str, dict[str, float]]:
    return json.loads(_REF_PATH.read_text())


def _five_year_cap_setup() -> tuple[list[CashFlow], YieldTermStructureProtocol]:
    """Build the 5y Euribor3M cap leg used by the probe."""
    eval_date = Date.from_ymd(17, Month.January, 2024)
    curve = cast(
        YieldTermStructureProtocol,
        FlatForward.from_rate(
            eval_date, 0.05, Actual360(), Compounding.Continuous, Frequency.Annual
        ),
    )
    cal = TARGET()
    start = cal.advance(eval_date, 2, TimeUnit.Days)
    end = cal.advance(start, 5, TimeUnit.Years)
    idx = Euribor(Period(3, TimeUnit.Months), curve)
    schedule = Schedule.from_rule(
        start, end, Period(3, TimeUnit.Months), cal,
        BusinessDayConvention.ModifiedFollowing,
        BusinessDayConvention.ModifiedFollowing,
        DateGeneration.Backward, False,
    )
    leg = ibor_leg(
        schedule, idx, [1_000_000.0],
        payment_adjustment=BusinessDayConvention.ModifiedFollowing,
        fixing_days=2,
    )
    set_coupon_pricer(leg, IborCouponPricer())
    return leg, curve


# --- BlackCapFloorEngine: Cap ---------------------------------------------


def test_black_cap_engine_npv_matches_probe(
    cluster_refs: dict[str, dict[str, float]],
) -> None:
    leg, curve = _five_year_cap_setup()
    cap = Cap(leg, [0.04])
    expected = cluster_refs["black_cap_5y_4pct"]
    cap.set_pricing_engine(BlackCapFloorEngine(curve, expected["vol"]))
    # LOOSE: per-optionlet sum of Black formulas + discount lookups
    # accumulates float work.
    tolerance.loose(cap.npv(), expected["npv"])


def test_black_cap_engine_writes_per_optionlet_results(
    cluster_refs: dict[str, dict[str, float]],
) -> None:
    leg, curve = _five_year_cap_setup()
    cap = Cap(leg, [0.04])
    expected = cluster_refs["black_cap_5y_4pct"]
    cap.set_pricing_engine(BlackCapFloorEngine(curve, expected["vol"]))
    cap.npv()
    extras = cap.additional_results()
    n = len(leg)
    assert len(extras["optionletsPrice"]) == n
    assert len(extras["optionletsDiscountFactor"]) == n
    # Vega is positive.
    assert extras["vega"] > 0.0


# --- BlackCapFloorEngine: Floor -------------------------------------------


def test_black_floor_engine_npv_matches_probe(
    cluster_refs: dict[str, dict[str, float]],
) -> None:
    leg, curve = _five_year_cap_setup()
    floor = Floor(leg, [0.04])
    expected = cluster_refs["black_floor_5y_4pct"]
    floor.set_pricing_engine(BlackCapFloorEngine(curve, expected["vol"]))
    tolerance.loose(floor.npv(), expected["npv"])


# --- BachelierCapFloorEngine: Cap -----------------------------------------


def test_bachelier_cap_engine_npv_matches_probe(
    cluster_refs: dict[str, dict[str, float]],
) -> None:
    leg, curve = _five_year_cap_setup()
    cap = Cap(leg, [0.04])
    expected = cluster_refs["bachelier_cap_5y_4pct"]
    cap.set_pricing_engine(BachelierCapFloorEngine(curve, expected["vol"]))
    tolerance.loose(cap.npv(), expected["npv"])
