"""BlackSwaptionEngine + BachelierSwaptionEngine cross-validation vs C++ probe.

Reference values: ``migration-harness/references/cluster/l4e.json``
generated by ``migration-harness/cpp/probes/cluster_l4e/probe.cpp``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import cast

import pytest

from pquantlib.daycounters.actual_360 import Actual360
from pquantlib.daycounters.thirty_360 import Convention, Thirty360
from pquantlib.exercise import EuropeanExercise
from pquantlib.indexes.ibor.euribor import Euribor
from pquantlib.instruments.swap import SwapType
from pquantlib.instruments.swaption import Swaption
from pquantlib.instruments.vanilla_swap import VanillaSwap
from pquantlib.pricingengines.swap.discounting_swap_engine import DiscountingSwapEngine
from pquantlib.pricingengines.swaption.bachelier_swaption_engine import (
    BachelierSwaptionEngine,
)
from pquantlib.pricingengines.swaption.black_swaption_engine import BlackSwaptionEngine
from pquantlib.termstructures.protocols import YieldTermStructureProtocol
from pquantlib.termstructures.yield_.flat_forward import FlatForward
from pquantlib.testing import tolerance
from pquantlib.time.business_day_convention import BusinessDayConvention
from pquantlib.time.calendars.target import TARGET
from pquantlib.time.compounding import Compounding
from pquantlib.time.date import Date
from pquantlib.time.date_generation import DateGeneration
from pquantlib.time.frequency import Frequency
from pquantlib.time.month import Month
from pquantlib.time.period import Period
from pquantlib.time.schedule import Schedule
from pquantlib.time.time_unit import TimeUnit

_REF_PATH = (
    Path(__file__).resolve().parents[4] / "migration-harness/references/cluster/l4e.json"
)


@pytest.fixture(scope="module")
def cluster_refs() -> dict[str, dict[str, float]]:
    return json.loads(_REF_PATH.read_text())


def _five_by_ten_receiver_swaption() -> tuple[Swaption, YieldTermStructureProtocol]:
    """Build the 5y10y receiver swaption used by the probe.

    Mirrors the C++ setup exactly: TARGET calendar, eval_date = 17 Jan 2024,
    FlatForward(5%, Actual360, Continuous, Annual), Euribor3M, 1M EUR notional,
    semi-annual Thirty360 fixed leg, quarterly Actual360 float leg,
    Backward schedule generation, fixed rate = 3%.
    """
    eval_date = Date.from_ymd(17, Month.January, 2024)
    curve = cast(
        YieldTermStructureProtocol,
        FlatForward.from_rate(
            eval_date, 0.05, Actual360(), Compounding.Continuous, Frequency.Annual
        ),
    )
    cal = TARGET()
    settle = cal.advance(eval_date, 5, TimeUnit.Years)
    end = cal.advance(settle, 10, TimeUnit.Years)
    idx = Euribor(Period(3, TimeUnit.Months), curve)
    fixed_sched = Schedule.from_rule(
        settle, end, Period(6, TimeUnit.Months), cal,
        BusinessDayConvention.ModifiedFollowing,
        BusinessDayConvention.ModifiedFollowing,
        DateGeneration.Backward, False,
    )
    float_sched = Schedule.from_rule(
        settle, end, Period(3, TimeUnit.Months), cal,
        BusinessDayConvention.ModifiedFollowing,
        BusinessDayConvention.ModifiedFollowing,
        DateGeneration.Backward, False,
    )
    swap = VanillaSwap(
        SwapType.Receiver, 1_000_000.0,
        fixed_sched, 0.03, Thirty360(Convention.BondBasis),
        float_sched, idx, 0.0, idx.day_counter(),
    )
    swap.set_pricing_engine(DiscountingSwapEngine(curve))
    exercise = EuropeanExercise(settle)
    return Swaption(swap, exercise), curve


# --- BlackSwaptionEngine ---------------------------------------------------


def test_black_swaption_engine_npv_matches_probe(
    cluster_refs: dict[str, dict[str, float]],
) -> None:
    swaption, curve = _five_by_ten_receiver_swaption()
    expected = cluster_refs["black_swaption_5y10y"]
    swaption.set_pricing_engine(BlackSwaptionEngine(curve, expected["vol"]))
    # LOOSE: NPV combines schedule-driven discount lookups, par-coupon
    # forward forecasting, and the Black formula — small idiom drift can
    # accumulate past TIGHT. 1e-8 covers genuine bit-equivalence.
    tolerance.loose(swaption.npv(), expected["npv"])


def test_black_swaption_engine_writes_additional_results(
    cluster_refs: dict[str, dict[str, float]],
) -> None:
    swaption, curve = _five_by_ten_receiver_swaption()
    expected = cluster_refs["black_swaption_5y10y"]
    swaption.set_pricing_engine(BlackSwaptionEngine(curve, expected["vol"]))
    swaption.npv()
    extras = swaption.additional_results()
    # vega + annuity + atmForward must all be populated for the
    # SwaptionHelper implied-vol Brent solver to work.
    assert "vega" in extras
    assert "annuity" in extras
    assert "atmForward" in extras
    assert "stdDev" in extras
    assert "impliedVolatility" in extras
    # Vega is positive (Black option's price is monotone in vol).
    assert extras["vega"] > 0.0


# --- BachelierSwaptionEngine ----------------------------------------------


def test_bachelier_swaption_engine_npv_matches_probe(
    cluster_refs: dict[str, dict[str, float]],
) -> None:
    swaption, curve = _five_by_ten_receiver_swaption()
    expected = cluster_refs["bachelier_swaption_5y10y"]
    swaption.set_pricing_engine(BachelierSwaptionEngine(curve, expected["vol"]))
    tolerance.loose(swaption.npv(), expected["npv"])


def test_bachelier_swaption_engine_writes_vega(
    cluster_refs: dict[str, dict[str, float]],
) -> None:
    swaption, curve = _five_by_ten_receiver_swaption()
    expected = cluster_refs["bachelier_swaption_5y10y"]
    swaption.set_pricing_engine(BachelierSwaptionEngine(curve, expected["vol"]))
    swaption.npv()
    extras = swaption.additional_results()
    assert extras["vega"] > 0.0
