"""Cross-validation of Garch11 against C++ v1.43.

# C++ parity: ql/models/volatility/garch.{hpp,cpp} @ v1.43.
# Reference: migration-harness/cpp/probes/v143_models_volatility/probe.cpp,
# ``emitGarch``.

The input series is 400 points generated by the upstream test-suite's own
generator (``MersenneTwisterUniformRng(48)`` + ``InverseCumulativeNormal``
driving a ``Garch11(0.2, 0.3, 0.4)``, test-suite/garch.cpp:89-99) and is
carried IN the reference JSON, so both sides read identical doubles rather
than having to reproduce the RNG.

Tolerance tiers used here
-------------------------
Everything that is pure arithmetic — ``to_r2``, the autocovariances, the
static ``cost_function``, ``forecast``, ``calculate``, and the *initial
guesses* — is asserted at TIGHT.

The four fully-optimized ``alpha`` / ``beta`` / ``omega`` triples are not,
and the bound used is derived rather than chosen: ``calibrate_r2`` runs
``Simplex(0.001)`` under ``EndCriteria(10000, 500, 1e-8, 1e-8, 1e-8)``
(garch.cpp:396-397), and ``Simplex::minimize`` stops when the mean Euclidean
distance of the simplex vertices from their centroid falls below
``root_epsilon`` — i.e. 1e-8 (simplex.cpp:145/196-198, mirrored in
pquantlib/math/optimization/simplex.py). The converged point is therefore
only pinned to a radius of 1e-8 in parameter space, and that is exactly what
C++ itself shows on this series: its ``MomentMatchingGuess`` and
``GammaGuess`` answers differ from each other by 4e-8 in ``alpha`` while
agreeing on ``logLikelihood`` to 4e-16. So the parameters are checked at
``abs_tol = 1e-8`` (the optimizer's own stated x-resolution) and the
log-likelihood — the quantity that IS determined — stays at TIGHT.
"""

from __future__ import annotations

import math
from typing import Any

import numpy as np
import pytest

from pquantlib.exceptions import LibraryException
from pquantlib.math.optimization.constraint import NoConstraint
from pquantlib.math.optimization.end_criteria import EndCriteria, Type
from pquantlib.math.optimization.optimization_method import OptimizationMethod
from pquantlib.math.optimization.problem import Problem
from pquantlib.math.optimization.simplex import Simplex
from pquantlib.models.volatility.garch import (
    Garch11,
    Garch11Mode,
    _autocovariances,  # pyright: ignore[reportPrivateUsage]  # ported ql/math/autocovariance.hpp helper; pinned deliberately
)
from pquantlib.testing import tolerance
from pquantlib.time.date import Date
from pquantlib.time.time_series import TimeSeries
from pquantlib.volatility_model import VolatilityCompositor

from .conftest import assert_series_matches

# The Simplex x-convergence radius; see the module docstring for the derivation.
_SIMPLEX_ROOT_EPSILON = 1e-8
_SIMPLEX_REASON = (
    "Simplex(0.001) stops when the mean vertex-to-centroid distance of the simplex "
    "drops below EndCriteria.root_epsilon = tol_level = 1e-8 (garch.cpp:396-397, "
    "simplex.cpp:145/196-198), so the converged parameters are only determined to "
    "that radius; C++'s own two modes differ by 4e-8 in alpha on this same series."
)


class DummyOptimizationMethod(OptimizationMethod):
    """Evaluates the cost at the starting point and stops.

    # C++ parity: test-suite/garch.cpp:36-42. Used to observe the INITIAL
    # GUESS with no optimization on top of it, which is what separates the
    # deterministic half of the calibration from the Simplex search.
    """

    def minimize(self, problem: Problem, end_criteria: EndCriteria) -> Type:
        del end_criteria
        problem.set_function_value(problem.value(problem.current_value))
        return Type.None_


@pytest.fixture(scope="module")
def garch(cpp: dict[str, Any]) -> dict[str, Any]:
    return cpp["garch"]


@pytest.fixture(scope="module")
def returns(garch: dict[str, Any]) -> list[float]:
    return list(garch["series"])


@pytest.fixture(scope="module")
def series(garch: dict[str, Any], returns: list[float]) -> TimeSeries[float]:
    return TimeSeries[float].from_first_date(Date(garch["start_serial"]), returns)


def _assert_calibration(actual: Garch11, expected: dict[str, Any], *, tier: str) -> None:
    if tier == "tight":
        tolerance.tight(actual.alpha(), expected["alpha"])
        tolerance.tight(actual.beta(), expected["beta"])
        tolerance.tight(actual.omega(), expected["omega"])
        tolerance.tight(actual.lt_vol(), expected["lt_vol"])
    else:
        for got, want in (
            (actual.alpha(), expected["alpha"]),
            (actual.beta(), expected["beta"]),
            (actual.omega(), expected["omega"]),
            (actual.lt_vol(), expected["lt_vol"]),
        ):
            tolerance.custom(
                got, want, abs_tol=_SIMPLEX_ROOT_EPSILON, rel_tol=0.0, reason=_SIMPLEX_REASON
            )
    tolerance.tight(actual.log_likelihood(), expected["log_likelihood"])
    assert int(actual.mode()) == expected["mode"]


# --- the deterministic inputs of the calibration ------------------------------


def test_to_r2_matches_cpp(garch: dict[str, Any], returns: list[float]) -> None:
    """# C++ parity: ``Garch11::to_r2`` (garch.hpp:157-168).

    The running weight ``w /= (w + 1)`` makes this an incremental arithmetic
    mean; an exponentially weighted one would give a different number.
    """
    r2, mean_r2 = Garch11.to_r2(returns)
    assert len(r2) == len(returns)
    for got, ret in zip(r2, returns, strict=True):
        tolerance.exact(got, ret * ret)
    tolerance.tight(mean_r2, garch["mean_r2"])
    # ...and it really is the plain mean of the squares.
    tolerance.custom(
        mean_r2,
        sum(r2) / len(r2),
        abs_tol=1e-13,
        rel_tol=1e-13,
        reason="incremental vs one-shot summation of 400 terms differ in rounding only",
    )


def test_autocovariances_match_cpp(garch: dict[str, Any], returns: list[float]) -> None:
    """# C++ parity: ``autocovariances`` (ql/math/autocovariance.hpp:96-110)
    as ``calibrate_r2`` calls it (garch.cpp:415-421).

    ``ql/math/autocovariance.hpp`` has no pquantlib module yet, so the helper
    lives inside garch.py; it is pinned here because every initial guess is
    built from its output.
    """
    r2, mean_r2 = Garch11.to_r2(returns)
    max_lag = int(math.sqrt(float(len(r2))))
    assert max_lag == garch["max_lag"]
    acf = _autocovariances([x - mean_r2 for x in r2], max_lag)
    assert len(acf) == max_lag + 1
    for got, want in zip(acf, garch["acf"], strict=True):
        tolerance.tight(got, want)


def test_static_cost_function_matches_cpp(garch: dict[str, Any], returns: list[float]) -> None:
    """# C++ parity: ``Garch11::costFunction`` (garch.hpp:237-249).

    Pinned at three fixed parameter triples so the objective is validated
    independently of any optimizer.
    """
    triples = zip(
        garch["cost_alpha"], garch["cost_beta"], garch["cost_omega"], garch["cost_values"], strict=True
    )
    for alpha, beta, omega, expected in triples:
        tolerance.tight(Garch11.cost_function(returns, alpha, beta, omega), expected)


def test_cost_function_of_an_empty_series_is_zero() -> None:
    """# C++ parity: garch.hpp:248 — ``N > 0 ? retval/(2*N) : 0.0``."""
    assert Garch11.cost_function([], 0.2, 0.3, 0.2) == 0.0


# --- the explicitly parameterised model ---------------------------------------


def test_constructor_takes_the_long_term_variance_not_omega(garch: dict[str, Any]) -> None:
    """``Garch11(a, b, vl)``: ``omega() == vl * (1 - a - b)``.

    # C++ parity: garch.hpp:56-58 and :70. Reading the third argument as
    # omega would still reproduce alpha and beta and get every forecast wrong,
    # so the probe pins ``omega`` and ``ltVol`` separately.
    """
    model = Garch11(0.2, 0.3, 0.4)
    expected = garch["generator"]
    tolerance.exact(model.alpha(), expected["alpha"])
    tolerance.exact(model.beta(), expected["beta"])
    tolerance.exact(model.omega(), expected["omega"])
    tolerance.exact(model.lt_vol(), expected["lt_vol"])
    tolerance.exact(model.log_likelihood(), expected["log_likelihood"])
    assert int(model.mode()) == expected["mode"]
    assert model.mode() is Garch11Mode.BestOfTwo
    assert model.omega() != model.lt_vol()


def test_forecast_matches_cpp(garch: dict[str, Any]) -> None:
    """# C++ parity: garch.hpp:152-154."""
    model = Garch11(0.2, 0.3, 0.4)
    cases = zip(
        garch["forecast_r"], garch["forecast_sigma2"], garch["forecast_generator"], strict=True
    )
    for r, sigma2, expected in cases:
        tolerance.tight(model.forecast(r, sigma2), expected)


def test_forecast_over_several_horizons_matches_cpp(garch: dict[str, Any]) -> None:
    """Iterated one-step forecasts — the chain the generator itself walks."""
    model = Garch11(0.2, 0.3, 0.4)
    sigma2 = 0.0
    for expected in garch["forecast_chain_generator"]:
        sigma2 = model.forecast(0.15, sigma2)
        tolerance.tight(sigma2, expected)


def test_forecast_is_even_in_the_return() -> None:
    """``alpha * r * r`` — the sign of ``r`` must not matter."""
    model = Garch11(0.2, 0.3, 0.4)
    tolerance.exact(model.forecast(0.3, 0.05), model.forecast(-0.3, 0.05))


# --- calculate ----------------------------------------------------------------


def test_calculate_matches_the_upstream_test_suite_scenario(garch: dict[str, Any]) -> None:
    """Constant 0.1 over 10 days, model (0.2, 0.3, 0.4).

    # C++ parity: test-suite/garch.cpp:169-183. The values in the reference
    # are the upstream ``expected_calc`` table to six figures
    # (0.452769, 0.513323, 0.530141, ...), which makes this an independent
    # check that the PROBE is right as well as that the port is.
    """
    model = Garch11(0.2, 0.3, 0.4)
    flat: TimeSeries[float] = TimeSeries[float].from_first_date(Date(garch["start_serial"]), [0.1] * 10)
    assert_series_matches(model.calculate(flat), garch["calculate_flat"], tolerance.tight)


def test_calculate_shifts_forward_and_appends_a_synthetic_date(garch: dict[str, Any]) -> None:
    """Output starts one date late and ends one date PAST the input.

    # C++ parity: garch.cpp:386-388 — the final variance is filed under
    # ``last + (last - second_to_last)``, a date that is not in the input.
    """
    model = Garch11(0.2, 0.3, 0.4)
    start = Date(garch["start_serial"])
    flat: TimeSeries[float] = TimeSeries[float].from_first_date(start, [0.1] * 10)
    result = model.calculate(flat)
    assert result.size() == flat.size()
    assert result.first_date() == flat.dates()[1]
    assert result.last_date() == flat.last_date() + 1
    assert result.last_date() not in flat


def test_calculate_extrapolates_the_final_gap_not_a_single_day() -> None:
    """The synthetic date repeats the LAST GAP, which need not be one day."""
    model = Garch11(0.2, 0.3, 0.4)
    series: TimeSeries[float] = TimeSeries[float].from_pairs(
        [Date(45000), Date(45001), Date(45008)], [0.1, 0.2, 0.15]
    )
    result = model.calculate(series)
    assert result.last_date() == Date(45015)


def test_calculate_series_agrees_with_the_instance_method(garch: dict[str, Any]) -> None:
    """# C++ parity: garch.hpp:78-80 — the virtual overload just forwards."""
    model = Garch11(0.2, 0.3, 0.4)
    flat: TimeSeries[float] = TimeSeries[float].from_first_date(Date(garch["start_serial"]), [0.1] * 10)
    direct = Garch11.calculate_series(flat, model.alpha(), model.beta(), model.omega())
    assert list(direct.values()) == list(model.calculate(flat).values())
    assert list(direct.dates()) == list(model.calculate(flat).dates())


def test_calculate_needs_two_observations() -> None:
    """C++ decrements an iterator past ``begin()`` for the synthetic date."""
    model = Garch11(0.2, 0.3, 0.4)
    single: TimeSeries[float] = TimeSeries[float].from_first_date(Date(45000), [0.1])
    with pytest.raises(LibraryException, match="at least two observations"):
        model.calculate(single)


# --- calibration --------------------------------------------------------------

_MODES = [
    (Garch11Mode.MomentMatchingGuess, "guess_moment_matching", "calibrated_moment_matching"),
    (Garch11Mode.GammaGuess, "guess_gamma", "calibrated_gamma"),
    (Garch11Mode.BestOfTwo, "guess_best_of_two", "calibrated_best_of_two"),
    (
        Garch11Mode.DoubleOptimization,
        "guess_double_optimization",
        "calibrated_double_optimization",
    ),
]


@pytest.mark.parametrize(("mode", "guess_key", "_calibrated_key"), _MODES)
def test_initial_guess_matches_cpp(
    mode: Garch11Mode,
    guess_key: str,
    _calibrated_key: str,
    garch: dict[str, Any],
    series: TimeSeries[float],
) -> None:
    """The initial guess alone, with no optimization on top.

    # C++ parity: test-suite/garch.cpp:112-114 — a ``DummyOptimizationMethod``
    # plus ``EndCriteria(3, 2, 0, 0, 0)`` leaves the optimizer's answer equal
    # to its starting point, so this pins ``initialGuess1`` /
    # ``initialGuess2`` (garch.cpp:230-369) including their non-linear
    # least-squares refinement of the ACF fit. That whole path is
    # deterministic, hence TIGHT.
    """
    model = Garch11(series, mode)
    model.calibrate(series, DummyOptimizationMethod(), EndCriteria(3, 2, 0.0, 0.0, 0.0))
    _assert_calibration(model, garch[guess_key], tier="tight")


@pytest.mark.parametrize(("mode", "_guess_key", "calibrated_key"), _MODES)
def test_calibration_matches_cpp(
    mode: Garch11Mode,
    _guess_key: str,
    calibrated_key: str,
    garch: dict[str, Any],
    series: TimeSeries[float],
) -> None:
    """Full ``Simplex(0.001)`` calibration from the constructor.

    # C++ parity: garch.hpp:60-63 (ctor) -> garch.hpp:81-84 (calibrate) ->
    # garch.cpp:393-500. See the module docstring for why the parameters use
    # the optimizer's own 1e-8 x-resolution while the log-likelihood is TIGHT.
    """
    _assert_calibration(Garch11(series, mode), garch[calibrated_key], tier="simplex")


def test_calibrate_after_construction_reproduces_the_constructor(
    garch: dict[str, Any], series: TimeSeries[float]
) -> None:
    """``calibrate(ts)`` is what the ``(ts, mode)`` constructor calls.

    # C++ parity: garch.hpp:62 — the ctor body is exactly ``calibrate(qs)``.
    """
    model = Garch11(series, Garch11Mode.BestOfTwo)
    model.calibrate(series)
    _assert_calibration(model, garch["calibrated_best_of_two"], tier="simplex")


def test_calibrate_accepts_a_plain_sequence_of_returns(
    garch: dict[str, Any], series: TimeSeries[float], returns: list[float]
) -> None:
    """# C++ parity: the ``ForwardIterator`` overloads (garch.hpp:109-150).

    C++ has both ``calibrate(time_series)`` and ``calibrate(begin, end)``;
    the latter takes raw values, and a plain Python sequence stands in for it.
    Both must give bit-identical results because C++'s series overload just
    calls ``values()``.
    """
    from_series = Garch11(series, Garch11Mode.BestOfTwo)
    from_values = Garch11(0.0, 0.0, 1.0)
    from_values.calibrate(returns)
    tolerance.exact(from_values.alpha(), from_series.alpha())
    tolerance.exact(from_values.beta(), from_series.beta())
    tolerance.exact(from_values.omega(), from_series.omega())
    tolerance.exact(from_values.log_likelihood(), from_series.log_likelihood())
    _assert_calibration(from_values, garch["calibrated_best_of_two"], tier="simplex")


def test_default_mode_is_best_of_two(garch: dict[str, Any], series: TimeSeries[float]) -> None:
    """# C++ parity: garch.hpp:60 — ``Mode mode = BestOfTwo``."""
    model = Garch11(series)
    assert model.mode() is Garch11Mode.BestOfTwo
    _assert_calibration(model, garch["calibrated_best_of_two"], tier="simplex")


def test_omega_round_trips_through_the_vl_division(series: TimeSeries[float]) -> None:
    """``calibrate`` stores omega in ``vl_``, then divides by gamma.

    # C++ parity: garch.hpp:114-116 — ``vl_ /= gamma_`` right after
    # ``calibrate_r2`` wrote omega into it, so ``omega() == vl * gamma``
    # returns the optimizer's omega back unchanged.
    """
    model = Garch11(series, Garch11Mode.BestOfTwo)
    gamma = 1 - model.alpha() - model.beta()
    tolerance.tight(model.omega(), model.lt_vol() * gamma)


def test_calculate_with_calibrated_parameters_matches_cpp(
    garch: dict[str, Any], series: TimeSeries[float], returns: list[float]
) -> None:
    """End-to-end: calibrate, then run ``calculate`` on the first 12 returns.

    TIGHT is used because the BestOfTwo parameters this consumes reproduced
    C++ to 6e-14 here (see ``test_calibration_matches_cpp``); the assertion
    is therefore reporting the agreement actually observed, not a padded one.
    """
    model = Garch11(series, Garch11Mode.BestOfTwo)
    head: TimeSeries[float] = TimeSeries[float].from_first_date(
        Date(garch["start_serial"]), returns[:12]
    )
    assert_series_matches(
        model.calculate(head), garch["calculate_calibrated_head"], tolerance.tight
    )


def test_forecast_chain_with_calibrated_parameters_matches_cpp(
    garch: dict[str, Any], series: TimeSeries[float]
) -> None:
    model = Garch11(series, Garch11Mode.BestOfTwo)
    sigma2 = 0.0
    for expected in garch["forecast_chain_calibrated"]:
        sigma2 = model.forecast(0.15, sigma2)
        tolerance.tight(sigma2, expected)


# --- error paths --------------------------------------------------------------


def test_series_shorter_than_four_points_is_rejected() -> None:
    """# C++ parity: garch.cpp:410-411."""
    short: TimeSeries[float] = TimeSeries[float].from_first_date(Date(45000), [0.1, -0.2, 0.15])
    with pytest.raises(LibraryException, match="too short to fit GARCH"):
        Garch11(short)


def test_constant_zero_series_is_rejected() -> None:
    """# C++ parity: garch.cpp:412 — ``mean_r2 > 0``."""
    zeros: TimeSeries[float] = TimeSeries[float].from_first_date(Date(45000), [0.0] * 10)
    with pytest.raises(LibraryException, match="constant"):
        Garch11(zeros)


def test_three_argument_constructor_needs_all_three() -> None:
    with pytest.raises(LibraryException, match="needs all three parameters"):
        Garch11(0.2, 0.3)  # type: ignore[call-overload]  # pyright: ignore[reportCallIssue]


def test_series_constructor_rejects_a_third_argument() -> None:
    series: TimeSeries[float] = TimeSeries[float].from_first_date(Date(45000), [0.1, -0.2, 0.15, 0.05])
    with pytest.raises(LibraryException, match="no third argument"):
        Garch11(series, Garch11Mode.BestOfTwo, 0.4)  # type: ignore[call-overload]  # pyright: ignore[reportCallIssue]


def test_calibrate_with_an_initial_guess_needs_a_method(series: TimeSeries[float]) -> None:
    model = Garch11(0.2, 0.3, 0.4)
    with pytest.raises(LibraryException, match="needs a method and end criteria"):
        model.calibrate(series, initial_guess=np.array([0.2, 0.2, 0.3]))


def test_calibrate_r2_without_a_guess_needs_a_mode_and_mean(returns: list[float]) -> None:
    r2, _ = Garch11.to_r2(returns)
    with pytest.raises(LibraryException, match="needs both a mode and mean_r2"):
        Garch11.calibrate_r2(r2)


# --- interface ----------------------------------------------------------------


def test_is_a_volatility_compositor() -> None:
    """# C++ parity: garch.hpp:38."""
    assert isinstance(Garch11(0.2, 0.3, 0.4), VolatilityCompositor)


def test_mode_is_reachable_as_a_class_attribute() -> None:
    """``Garch11.Mode.BestOfTwo`` mirrors C++ ``Garch11::BestOfTwo``."""
    assert Garch11.Mode is Garch11Mode
    assert [int(m) for m in Garch11Mode] == [0, 1, 2, 3]
    assert Garch11.Mode.MomentMatchingGuess == 0
    assert Garch11.Mode.DoubleOptimization == 3


# --- the calibrate_r2 overload set --------------------------------------------


class RaisingOptimizationMethod(OptimizationMethod):
    """Always fails, to reach the ``catch (const std::exception&)`` fallbacks."""

    def minimize(self, problem: Problem, end_criteria: EndCriteria) -> Type:
        del problem, end_criteria
        raise LibraryException("deliberate optimizer failure")


def test_calibrate_r2_with_an_explicit_guess_returns_that_guess(returns: list[float]) -> None:
    """# C++ parity: garch.hpp:205 -> garch.cpp:502-510 -> garch.cpp:525-542.

    With an optimizer that does not move, the optimum read back is the guess
    itself, and the returned ``Problem`` carries the cost evaluated there —
    which must equal ``Garch11.cost_function`` at the same parameters, since
    the two differ only in whether they square the series themselves.
    """
    r2, _ = Garch11.to_r2(returns)
    guess = np.array([0.2, 0.2, 0.3], dtype=np.float64)  # [omega, alpha, beta]
    result = Garch11.calibrate_r2(
        r2,
        method=DummyOptimizationMethod(),
        end_criteria=EndCriteria(3, 2, 0.0, 0.0, 0.0),
        initial_guess=guess,
    )
    assert result.problem is not None
    tolerance.exact(result.omega, 0.2)
    tolerance.exact(result.alpha, 0.2)
    tolerance.exact(result.beta, 0.3)
    tolerance.tight(
        result.problem.function_value, Garch11.cost_function(returns, 0.2, 0.3, 0.2)
    )


def test_calibrate_r2_centers_r2_when_given_mean_r2(returns: list[float]) -> None:
    """``mean_r2`` alongside a guess subtracts the mean first.

    # C++ parity: garch.cpp:512-523 — the overload that takes both builds a
    # centered copy and forwards it. The observable consequence is that the
    # reported cost is the cost of the CENTERED series, so it must differ from
    # the uncentered one and match a hand-centered call.
    """
    r2, mean_r2 = Garch11.to_r2(returns)
    guess = np.array([0.2, 0.2, 0.3], dtype=np.float64)
    kwargs: dict[str, Any] = {
        "method": DummyOptimizationMethod(),
        "end_criteria": EndCriteria(3, 2, 0.0, 0.0, 0.0),
        "initial_guess": guess,
    }
    centered_inside = Garch11.calibrate_r2(r2, mean_r2=mean_r2, **kwargs)
    centered_outside = Garch11.calibrate_r2([x - mean_r2 for x in r2], **kwargs)
    uncentered = Garch11.calibrate_r2(r2, **kwargs)

    assert centered_inside.problem is not None
    assert centered_outside.problem is not None
    assert uncentered.problem is not None
    tolerance.exact(
        centered_inside.problem.function_value, centered_outside.problem.function_value
    )
    assert centered_inside.problem.function_value != uncentered.problem.function_value


def test_calibrate_r2_default_constraint_rejects_a_non_stationary_guess(
    returns: list[float],
) -> None:
    """The default box is ``0 <= alpha+beta < 1 - 1e-8`` (garch.cpp:507).

    ``Simplex`` requires the initial guess to be feasible, so a guess with
    ``alpha + beta == 1`` must be refused rather than silently optimized.
    """
    r2, _ = Garch11.to_r2(returns)
    with pytest.raises(LibraryException, match="not in the feasible region"):
        Garch11.calibrate_r2(
            r2,
            method=Simplex(0.001),
            end_criteria=EndCriteria(100, 10, 1e-8, 1e-8, 1e-8),
            initial_guess=np.array([0.2, 0.5, 0.5], dtype=np.float64),
        )


def test_calibrate_r2_accepts_an_explicit_constraint(returns: list[float]) -> None:
    """# C++ parity: garch.hpp:227 — the overload that takes ``Constraint&``.

    ``NoConstraint`` admits the same guess the default box refuses, proving the
    argument is actually consulted rather than ignored.
    """
    r2, _ = Garch11.to_r2(returns)
    result = Garch11.calibrate_r2(
        r2,
        method=DummyOptimizationMethod(),
        constraints=NoConstraint(),
        end_criteria=EndCriteria(3, 2, 0.0, 0.0, 0.0),
        initial_guess=np.array([0.2, 0.5, 0.5], dtype=np.float64),
    )
    tolerance.exact(result.alpha, 0.5)
    tolerance.exact(result.beta, 0.5)


def test_calibrate_r2_rejects_a_mode_together_with_a_constraint(returns: list[float]) -> None:
    """No C++ overload takes both, so the combination is a caller error."""
    r2, mean_r2 = Garch11.to_r2(returns)
    with pytest.raises(LibraryException, match="mode and an explicit constraint"):
        Garch11.calibrate_r2(
            r2, mode=Garch11Mode.BestOfTwo, mean_r2=mean_r2, constraints=NoConstraint()
        )


def test_calibrate_r2_rejects_a_method_without_end_criteria(returns: list[float]) -> None:
    r2, mean_r2 = Garch11.to_r2(returns)
    with pytest.raises(LibraryException, match="together or not at all"):
        Garch11.calibrate_r2(
            r2, mode=Garch11Mode.BestOfTwo, mean_r2=mean_r2, method=Simplex(0.001)
        )


@pytest.mark.parametrize(
    ("mode", "guess_key"),
    [
        (Garch11Mode.MomentMatchingGuess, "guess_moment_matching"),
        (Garch11Mode.BestOfTwo, "guess_best_of_two"),
        (Garch11Mode.DoubleOptimization, "guess_double_optimization"),
    ],
)
def test_a_failing_optimizer_falls_back_to_the_initial_guess(
    mode: Garch11Mode,
    guess_key: str,
    garch: dict[str, Any],
    series: TimeSeries[float],
) -> None:
    """# C++ parity: garch.cpp:450-459 and :471/:483.

    When every optimization attempt throws, C++ keeps the initial guess and
    returns a NULL ``Problem``, which makes ``calibrate`` fall back to
    ``-costFunction(begin, end)`` over the RAW returns (garch.hpp:117-118)
    instead of ``-problem->functionValue()`` over ``r2``. Those two happen to
    agree, so the fallback must reproduce the pinned guess block exactly —
    including its log-likelihood.

    ``GammaGuess`` is excluded because with a failing optimizer the
    ``mode != DoubleOptimization`` branch picks ``opt1`` whenever
    ``fCost1 <= fCost2``, and for ``GammaGuess`` ``fCost1`` is
    ``QL_MAX_REAL`` — a different, already-covered selection path.
    """
    model = Garch11(series, mode)
    model.calibrate(series, RaisingOptimizationMethod(), EndCriteria(3, 2, 0.0, 0.0, 0.0))
    _assert_calibration(model, garch[guess_key], tier="tight")


def test_a_failing_optimizer_under_gamma_guess_falls_back_to_the_gamma_guess(
    garch: dict[str, Any], series: TimeSeries[float]
) -> None:
    """``GammaGuess`` leaves ``fCost1`` at ``QL_MAX_REAL``, so ``opt2`` wins.

    # C++ parity: garch.cpp:430-440 — ``opt1`` is never even computed in this
    # mode, and garch.cpp:455-458 then selects ``opt2``.
    """
    model = Garch11(series, Garch11Mode.GammaGuess)
    model.calibrate(series, RaisingOptimizationMethod(), EndCriteria(3, 2, 0.0, 0.0, 0.0))
    _assert_calibration(model, garch["guess_gamma"], tier="tight")


def test_calibrate_with_an_explicit_initial_guess_bypasses_the_mode(
    returns: list[float], series: TimeSeries[float]
) -> None:
    """# C++ parity: garch.hpp:136-150 — the mode is not consulted at all."""
    guess = np.array([0.2, 0.2, 0.3], dtype=np.float64)
    model = Garch11(series, Garch11Mode.GammaGuess)
    model.calibrate(
        series,
        DummyOptimizationMethod(),
        EndCriteria(3, 2, 0.0, 0.0, 0.0),
        initial_guess=guess,
    )
    tolerance.exact(model.alpha(), 0.2)
    tolerance.exact(model.beta(), 0.3)
    tolerance.tight(model.omega(), 0.2)
    tolerance.tight(model.log_likelihood(), -Garch11.cost_function(returns, 0.2, 0.3, 0.2))
    # The mode is remembered even though it was not used.
    assert model.mode() is Garch11Mode.GammaGuess
